STATES=('--Select State--',
        'None',
    'Andaman and Nicobar Islands(AN)',
    'Andhra Pradesh (AP)',
    'Arunachal Pradesh (AR)',
    'Assam (AS)',
    'Bihar (BR)',
    'Chandigarh (CH)',
    'Chhattisgarh (CG)',
    'Dadra and Nagar Haveli (DN)',
    'Daman and Diu (DD)',
    'Goa (GA)',
    'Gujarat (GJ)',
    'Haryana (HR)',
    'Himachal Pradesh (HP)',
    'Jammu and Kashmir (JK)',
    'Jharkhand (JH)',
    'Karnataka (KA)',
    'Kerala (KL)',
    'Lakshadweep (LD)',
    'Madhya Pradesh (MP)',
    'Maharashtra (MH)',
    'Manipur (MN)',
    'Meghalaya (ML)',
    'Mizoram (MZ)',
    'Nagaland (NL)',
    'National Capital Territory of Delhi (DL)',
    'Odisha(OR)',
    'Pondicherry (PY)',
    'Punjab (PB)',
    'Rajasthan (RJ)',
    'Sikkim (SK)',
    'Tamil Nadu (TN)',
    'Telangana (TS)',
    'Tripura (TR)',
    'Uttar Pradesh (UP)',
    'Uttarakhand (UK)',
    'West Bengal (WB)')



CITIES=('--Select City--',
        'None',
    'Ahmedabad',
	'Ahmednagar',
	'Allahabad',
	'Alappuzha',
	'Ambala',
	'Amritsar',
    'Anand',
    'Anantapur',
    'Armoor',
    'Asifabad',
    'Aurangabad',
	'Banswara',
	'Bardoli',
	'Bari Brahman',
    'Bargarh',
    'Bengaluru',
    'Bheeramguda',
    'Bhopal',
    'Bhubaneswar',
    'Chandigarh',
    'Chennai',
    'Chikmagalur',
    'Coimbatore',
    'Dadri',
    'Delhi',
    'Delhi South',
	'Devarapalli',
	'Durgapur',
    'Ernakulam',
    'Faridabad',
	'Gajraula',
    'Goa',    
	'Gorakhpur',
    'Ghaziabad',
	'Greater Noida',
    'Gulbarga',
    'Guntur',
    'Gurgaon',
	'Haldwani',
    'Hisar',
	'Hoshiarpur',
    'Hubli',
    'Huzurabad',
    'Hyderabad',
	'Idukki',
	'Indirapuram',
    'Indore',
    'Jaipur',
	'Jalandhar',
	'Jamshedpur',
	'Jhunjhunu',
    'Jodhpur',
	'Kannur',
	'Kasaragod',
	'Kapurthala',
    'Karimnagar',
    'Khammam',
    'Kochi',
    'Kodad',
    'Kolkata',
    'Kolhapur',
	'Kollam',
    'Kota',
	'Kottayam',
    'Kozhikode',
    'Kullu',
    'Kurnool',
    'Ludhiana',
    'Lucknow',
	'Madhira',
	'Malappuram',
    'Mangalore',
	'Meerut',
    'Mohali',
    'Mumbai',
    'Mumbai North',
    'Mumbai South',
    'Mysore',
    'Nagercoil',
    'Nagpur',
    'Nalgonda',
    'Nanded',
    'Nasik',
	'Navsari',
	'Navi Mumbai',
	'Nizamabad',
    'Noida',
    'Panaji',
	'Palakkad',
	'Pathanamthitta',
	'Patna',
    'Pondicherry',
    'Proddatur',
    'Pune',
    'Raigarh',
	'Rajahmundry',
	'Rampur',
	'Rewari',
    'Rohtak',
    'Salem',
    'Secunderabad',
    'Siddipet',
	'Sikar',
	'Silchar',
	'Siliguri',
	'Siwan',
    'Srungavarapukota',
    'Surat',
    'Thane',
	'Thrissur',
    'Trivandrum',
    'Udaipur',
	'Vadodara',
	'Valsad',
    'Vijayawada',
    'Warangal',
	'Wayanad',
    'Zirakpur'
    )


REGIONS=('None',
         'BLR',
         'PUJ',
         'MAH',
         'DLH',
         'HYD',
         'CHN'
         )



