STATES=('--Select State--',
        'None',
    'Andaman and Nicobar Islands(AN)',
    'Andhra Pradesh (AP)',
    'Arunachal Pradesh (AR)',
    'Assam (AS)',
    'Bihar (BR)',
    'Chandigarh (CH)',
    'Chhattisgarh (CG)',
    'Dadra and Nagar Haveli (DN)',
    'Daman and Diu (DD)',
    'Goa (GA)',
    'Gujarat (GJ)',
    'Haryana (HR)',
    'Himachal Pradesh (HP)',
    'Jammu and Kashmir (JK)',
    'Jharkhand (JH)',
    'Karnataka (KA)',
    'Kerala (KL)',
    'Lakshadweep (LD)',
    'Madhya Pradesh (MP)',
    'Maharashtra (MH)',
    'Manipur (MN)',
    'Meghalaya (ML)',
    'Mizoram (MZ)',
    'Nagaland (NL)',
    'National Capital Territory of Delhi (DL)',
    'Odisha(OR)',
    'Pondicherry (PY)',
    'Punjab (PB)',
    'Rajasthan (RJ)',
    'Sikkim (SK)',
    'Tamil Nadu (TN)',
    'Telangana (TS)',
    'Tripura (TR)',
    'Uttar Pradesh (UP)',
    'Uttarakhand (UK)',
    'West Bengal (WB)')



CITIES=('--Select City--',
    'None',
	'Agra',
    'Ahmedabad',
	'Ahmednagar',
	'Ajmer',
	'Alappuzha/Alleppey',
	'Allahabad',
	'Alwar',
	'Ambala',
	'Ambikapur',
	'Amritsar',
    'Anand',
    'Anantapur',
	'Armoor',
    'Asifabad',
	'Attur',
    'Aurangabad',
	'Balaghat',
	'Bangarapet',
	'Banswara',
	'Bardoli',
	'Bargarh',
	'Bari Brahmana',
	'Bathinda',
    'Bengaluru',
	'Bharatpur',
	'Bhawani Mandi',
    'Bheeramguda',
	'Bhilai',
    'Bhopal',
    'Bhubaneswar',
	'Bikaner',
	'Bilaspur',
	'Bodinayakanur',
    'Chandigarh',
    'Chennai',
    'Chikmagalur',
	'Chomu',
    'Coimbatore',
	'Cuttack',
    'Dadri',
	'Dausa',
    'Delhi',
    'Delhi South',
	'Dera Bassi',
	'Devarapalli',
	'Dhamtari',
	'Dharmapuri',
	'Dindigul',
	'Durgapur',
	'Eluru',
    'Ernakulam',
    'Faridabad',
	'Gajraula',
	'Gangtok',
	'Ghaziabad',
    'Goa',
	'Gondia',
	'Gorakhpur',
    'Greater Noida',
	'Gudivada',
    'Gulbarga',
    'Guntur',
	'Gurdaspur',
    'Gurgaon',
	'Guwahati',
        'Gwalior',
	'Haldwani',
	'Hanamkonda',
	'Hardoi',
	'Hassan',
    'Hisar',
	'Hoshiarpur',
    'Hubli',
    'Huzurabad',
    'Hyderabad',
	'Idukki',
	'Indirapuram',
    'Indore',
	'Jabalpur',
	'Jaggaiahpet',
    'Jaipur',
	'Jaisalmer',
	'Jalandhar',
	'Jamshedpur',
	'Jhunjhunu',
	'Jobner',
    'Jodhpur',
	'Kannur',
	'Kanyakumari',
	'Kapurthala',
	'Karimnagar',
	'Kasaragod',
	'Kashipur',    
    'Khammam',
	'Kharar',
    'Kochi',
    'Kodad',
	'Kolhapur',
    'Kolkata',
    'Kollam',
	'Kopargaon',
    'Kota',
	'Kottayam',
    'Kozhikode/Calicut',
	'Krishnarajpet',
    'Kullu',
	'Kurnool',
	'Kurud',
	'Latur',
	'Lucknow',
    'Ludhiana',
    'Madhira',
	'Malappuram',
	'Mandya',
	'Manesar',
    'Mangalore',
	'Meerut',
	'Mhow',
    'Mohali',
	'Mudaliarpet',
    'Mumbai',
    'Mumbai North',
    'Mumbai South',
    'Mysore',
    'Nagercoil',
    'Nagpur',
    'Nalgonda',
    'Nanded',
    'Nashik',
	'Navi Mumbai',
	'Navsari',
	'Nizamabad',
    'Noida',
	'Palakkad',
	'Palghar',
	'Pali',
	'Panchkula',
	'Pandavapura',
	'Panipat',
    'Panjim',
	'Panvel',
	'Parli Vaijnath',
	'Pathanamthitta',
	'Patiala',
	'Patna',
    'Pondicherry',
    'Proddatur',
    'Pune',
	'Puri',
	'Rahuri',
	'Raichur',
	'Raigarh',
	'Raipur',
	'Rajahmundry',
	'Rajkot',
	'Rajnandgaon',
	'Rajsamand',
	'Ramachandrapurm',
	'Rampur',
	'Ranchi',
	'Ratlam',
	'Reddiyur',
	'Rewari',
    'Rohtak',
	'Rupnagar(Rupar/Ropar)',
    'Salem',
	'Sangamner',
    'Secunderabad',
	'Shankarpalli',
	'Shimoga',
	'Shirdi',
    'Siddipet',
	'Sikar',
	'Silchar',
	'Siliguri',
	'Siwan',
	'Sri Ganganagar',
	'Srirangapatna',
    'Srungavarapukota',
    'Surat',
    'Thane',
	'Thoothukudi',
	'Thrissur',
	'Tirunelveli',
	'Tiruppur',
    'Trivandrum',
	'Tumsar',
    'Udaipur',
	'Ujjain',
	'Vadodara',
	'Valsad',
	'Vedaranniyam',
    'Vijayawada',
	'Visakhapatnam',
    'Warangal',
	'Wayanad',
    'Zirakpur',
    'ZZZZ'
    )


REGIONS=('None',
         'BLR',
         'PUJ',
         'MAH',
         'DLH',
         'HYD',
         'CHN'
         )


#
