INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('1', 'G0101', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('2', 'G0102', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('3', 'G0103', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('4', 'G0104', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('5', 'G0200', 'bite wing,IOPA');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('6', 'G0220', 'x-ray,IOPA');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('7', 'G0240', 'OPG,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('8', 'G0250', 'Cephalogram,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('9', 'G0260', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('10', 'G0400', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('11', 'G0410', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('12', 'G0420', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('13', 'G0430', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('14', 'G1001', 'scaling,cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('15', 'G1002', 'scaling,cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('16', 'G1013', 'scaling,cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('17', 'G1011', 'scaling,cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('18', 'G1012', 'scaling,cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('19', 'G1101', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('20', 'G1102', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('21', 'G1103', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('22', 'G1120', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('23', 'G1200', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('24', 'G1210', 'Pit and fissure sealants,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('25', 'G1220', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('26', 'G1300', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('27', 'G1310', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('28', 'G1320', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('29', 'G1330', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('30', 'G1340', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('31', 'G1350', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('32', 'G1360', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('33', 'G1370', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('34', 'G2000', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('35', 'G2010', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('36', 'G2020', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('37', 'G2030', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('38', 'G2040', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('39', 'G2050', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('40', 'G2060', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('41', 'G2070', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('42', 'G2100', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('43', 'G2110', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('44', 'G2120', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('45', 'G2130', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('46', 'G2140', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('47', 'G2150', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('48', 'G2160', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('49', 'G2180', 'inlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('50', 'G2181', 'onlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('51', 'G2182', 'inlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('52', 'G2183', 'onlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('53', 'G2190', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('54', 'G2191', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('55', 'G2192', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('56', 'G2195', 'Temporary filling,IRM');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('57', 'G2300', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('58', 'G2310', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('59', 'G2320', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('60', 'G2330', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('61', 'G2340', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('62', 'G2400', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('63', 'G2401', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('64', 'G2405', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('65', 'G2410', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('66', 'G2415', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('67', 'G2420', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('68', 'G2425', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('69', 'G2430', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('70', 'G2435', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('71', 'G2440', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('72', 'G2445', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('73', 'G2450', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('74', 'G2455', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('75', 'G2460', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('76', 'G2470', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('77', 'G2475', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('78', 'G2480', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('79', 'G2485', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('80', 'G2490', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('81', 'G2495', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('82', 'G2500', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('83', 'G2501', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('84', 'G2502', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('85', 'G2510', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('86', 'G2511', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('87', 'G2512', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('88', 'G2513', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('89', 'G2520', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('90', 'G2600', 'veneer,Laminates');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('91', 'G2610', 'veneer,Laminates');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('92', 'G2620', 'veneer,e- max');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('93', 'G3000', 'Pulp capping,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('94', 'G3010', 'Pulp capping,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('95', 'G3020', 'pulpotomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('96', 'G3030', 'pulpectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('97', 'G3210', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('98', 'G3215', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('99', 'G3220', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('100', 'G3225', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('101', 'G3230', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('102', 'G3235', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('103', 'G3310', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('104', 'G3320', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('105', 'G3330', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('106', 'G3340', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('107', 'G4000', 'deep scaling,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('108', 'G4010', 'deep scaling,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('109', 'G4100', 'Gingvectomy,Gingivoplasty');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('110', 'G4110', 'Gingvectomy,Gingivoplasty');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('111', 'G4120', 'Curettage,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('112', 'G4130', 'Gingvectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('113', 'G4140', 'Gingvectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('114', 'G4200', 'flap,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('115', 'G4220', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('116', 'G4300', 'Flap ,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('117', 'G4600', 'Bone graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('118', 'G4610', 'Bone graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('119', 'G4800', 'Splinting,splint');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('120', 'G4810', 'Splinting,splint');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('121', 'G5000', 'denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('122', 'G5001', 'Imported denture,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('123', 'G5002', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('124', 'G5003', 'BPS CD,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('125', 'G5010', 'denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('126', 'G5011', 'Imported denture,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('127', 'G5012', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('128', 'G5013', 'BPS CD,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('129', 'G5020', 'Immediate,Temporary');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('130', 'G5030', 'Immediate,Temporary');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('131', 'G5040', 'Flexible,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('132', 'G5050', 'Flexible,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('133', 'G5060', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('134', 'G5065', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('135', 'G5100', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('136', 'G5110', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('137', 'G5120', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('138', 'G5130', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('139', 'G5140', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('140', 'G5141', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('141', 'G5150', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('142', 'G5151', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('143', 'G5160', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('144', 'G5165', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('145', 'G5166', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('146', 'G5200', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('147', 'G5210', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('148', 'G5220', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('149', 'G5230', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('150', 'G5240', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('151', 'G5250', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('152', 'G5260', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('153', 'G5270', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('154', 'G5280', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('155', 'G5300', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('156', 'G5310', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('157', 'G5320', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('158', 'G5330', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('159', 'G5340', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('160', 'G5350', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('161', 'G5360', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('162', 'G5370', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('163', 'G5400', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('164', 'G5410', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('165', 'G5420', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('166', 'G5430', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('167', 'G5500', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('168', 'G5510', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('169', 'G5600', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('170', 'G5610', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('171', 'G7000', 'extraction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('172', 'G7005', 'extraction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('173', 'G7010', 'extraction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('174', 'G7011', 'extraction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('175', 'G7020', 'extraction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('176', 'G7030', 'wisdom,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('177', 'G7040', 'wisdom,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('178', 'G7050', 'wisdom,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('179', 'G7061', 'RS,root stumps');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('180', 'G7200', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('181', 'G7210', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('182', 'G7600', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('183', 'G9000', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('184', 'G9020', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('185', 'G9030', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('186', 'G9040', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('187', 'G9300', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('188', 'G9310', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('189', 'G9311', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('190', 'G9320', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('191', 'G9500', 'whitening,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('192', 'G9510', 'walking bleach,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('193', 'G9511', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('194', 'S0100', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('195', 'S1001', 'scaling,Cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('196', 'S1002', 'scaling,Cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('197', 'S1013', 'scaling,Cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('198', 'S1011', 'scaling,Cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('199', 'S1012', 'scaling,Cleaning');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('200', 'S1101', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('201', 'S1102', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('202', 'S1103', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('203', 'S1120', 'Fluoride,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('204', 'S1210', 'Pit and fissure sealants,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('205', 'S1300', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('206', 'S1310', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('207', 'S1320', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('208', 'S1330', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('209', 'S1340', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('210', 'S1350', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('211', 'S1360', 'Space maintainer,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('212', 'S1370', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('213', 'S2000', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('214', 'S2010', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('215', 'S2020', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('216', 'S2030', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('217', 'S2040', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('218', 'S2050', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('219', 'S2060', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('220', 'S2070', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('221', 'S2100', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('222', 'S2110', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('223', 'S2120', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('224', 'S2130', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('225', 'S2140', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('226', 'S2150', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('227', 'S2160', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('228', 'S2180', 'inlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('229', 'S2181', 'onlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('230', 'S2182', 'inlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('231', 'S2183', 'onlay,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('232', 'S2190', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('233', 'S2191', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('234', 'S2192', 'Restoration,Filling');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('235', 'S2195', 'Temporary filling,IRM');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('236', 'S2300', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('237', 'S2310', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('238', 'S2320', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('239', 'S2330', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('240', 'S2340', 'Core build up,Post');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('241', 'S2400', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('242', 'S2401', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('243', 'S2405', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('244', 'S2410', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('245', 'S2415', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('246', 'S2420', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('247', 'S2425', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('248', 'S2430', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('249', 'S2435', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('250', 'S2440', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('251', 'S2445', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('252', 'S2450', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('253', 'S2455', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('254', 'S2460', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('255', 'S2470', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('256', 'S2475', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('257', 'S2480', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('258', 'S2485', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('259', 'S2490', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('260', 'S2495', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('261', 'S2500', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('262', 'S2501', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('263', 'S2502', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('264', 'S2510', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('265', 'S2511', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('266', 'S2512', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('267', 'S2513', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('268', 'S2520', 'Crown,Cap');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('269', 'S2600', 'veneer,Laminates');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('270', 'S2610', 'veneer,Laminates');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('271', 'S2620', 'veneer,e- max');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('272', 'S3021', 'Pulp capping,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('273', 'S3022', 'Pulp capping,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('274', 'S3023', 'pulpotomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('275', 'S3024', 'pulpectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('276', 'S3210', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('277', 'S3215', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('278', 'S3220', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('279', 'S3225', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('280', 'S3230', 'RCT,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('281', 'S3235', 'Re-root canal,Re-RCT');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('282', 'S3240', 'Apexification,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('283', 'S3245', 'Apexogenisis,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('284', 'S3250', 'Apexification,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('285', 'S3255', 'Apexogenisis,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('286', 'S3310', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('287', 'S3320', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('288', 'S3330', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('289', 'S3340', 'Apicoectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('290', 'S3350', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('291', 'S3360', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('292', 'S3361', 'reimplantation,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('293', 'S4000', 'deep scaling,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('294', 'S4001', 'root planning,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('295', 'S4002', 'root planning,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('296', 'S4010', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('297', 'S4100', 'Gingivectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('298', 'S4110', 'Gingivectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('299', 'S4120', 'Curettage,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('300', 'S4130', 'Gingivectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('301', 'S4140', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('302', 'S4200', 'Flap ,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('303', 'S4201', 'Flap ,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('304', 'S4202', 'Flap,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('305', 'S4210', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('306', 'S4220', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('307', 'S4300', 'Flap,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('308', 'S4301', 'Flap,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('309', 'S4400', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('310', 'S4410', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('311', 'S4411', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('312', 'S4600', 'Graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('313', 'S4610', 'Graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('314', 'S4611', 'Guided tissue,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('315', 'S4612', 'Guided tissue,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('316', 'S4613', 'pedicle,soft tissue graft');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('317', 'S4614', 'pedicle,soft tissue graft');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('318', 'S4615', 'Graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('319', 'S4616', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('320', 'S4617', 'allograft,graft');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('321', 'S4618', 'graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('322', 'S4700', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('323', 'S4702', 'Crown lenghtening,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('324', 'S4703', 'Crown lenghtening,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('325', 'S4705', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('326', 'S4706', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('327', 'S4710', 'Gingivectomy,Gingivoplasty');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('328', 'S4711', 'Gingivectomy,Gingivoplasty');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('329', 'S4712', 'Gingivectomy,Gingivoplasty');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('330', 'S4713', 'Curettage,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('331', 'S4714', 'Curettage,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('332', 'S4715', 'Bleaching,whitening');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('333', 'S4720', 'Operculectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('334', 'S4721', 'Operculectomy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('335', 'S4722', 'removal,excision');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('336', 'S4723', 'removal,excision');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('337', 'S4724', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('338', 'S4800', 'Slpinting,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('339', 'S4810', 'Slpinting,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('340', 'S4850', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('341', 'S4910', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('342', 'S5000', 'denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('343', 'S5001', 'Imported denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('344', 'S5002', ',CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('345', 'S5003', 'BPS CD,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('346', 'S5010', 'denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('347', 'S5011', 'Imported denture,CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('348', 'S5012', ',CD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('349', 'S5013', 'BPS CD,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('350', 'S5020', 'Immediate,Temporary');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('351', 'S5030', 'Immediate,Temporary');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('352', 'S5040', 'Flexible,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('353', 'S5050', 'Flexible,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('354', 'S5060', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('355', 'S5065', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('356', 'S5100', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('357', 'S5110', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('358', 'S5120', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('359', 'S5130', 'partial,RPD');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('360', 'S5140', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('361', 'S5141', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('362', 'S5150', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('363', 'S5151', 'RPD,flexible');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('364', 'S5160', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('365', 'S5165', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('366', 'S5166', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('367', 'S5200', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('368', 'S5210', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('369', 'S5220', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('370', 'S5230', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('371', 'S5240', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('372', 'S5250', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('373', 'S5260', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('374', 'S5270', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('375', 'S5280', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('376', 'S5300', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('377', 'S5310', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('378', 'S5320', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('379', 'S5330', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('380', 'S5340', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('381', 'S5350', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('382', 'S5360', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('383', 'S5370', 'Relining,Reline');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('384', 'S5400', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('385', 'S5410', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('386', 'S5420', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('387', 'S5430', 'rebase,rebasing');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('388', 'S5500', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('389', 'S5510', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('390', 'S5600', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('391', 'S5610', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('392', 'S6450', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('393', 'S6500', 'Adin,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('394', 'S6501', 'Dentium,Zimmer,Ostem,Hitec');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('395', 'S6502', 'Nobel,Straumann');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('396', 'S6503', 'Nobel active,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('397', 'S6600', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('398', 'S6601', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('399', 'S6602', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('400', 'S6603', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('401', 'S6700', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('402', 'S6710', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('403', 'S6720', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('404', 'S6730', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('405', 'S6740', 'abutment,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('406', 'S6801', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('407', 'S6811', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('408', 'S7000', 'extraction,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('409', 'S7005', 'extraction,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('410', 'S7010', 'extraction,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('411', 'S7011', 'extraction,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('412', 'S7020', 'extraction,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('413', 'S7030', 'Wisdom ,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('414', 'S7040', 'Wisdom ,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('415', 'S7050', 'Wisdom ,removal');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('416', 'S7061', 'removal,Extraction');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('417', 'S7100', 'Fistula,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('418', 'S7110', 'reimplantation,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('419', 'S7120', 'exposure,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('420', 'S7125', 'exposure,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('421', 'S7130', 'Biopsy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('422', 'S7135', 'Biopsy,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('423', 'S7140', 'Surgical,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('424', 'S7145', 'Surgical,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('425', 'S7150', 'Bone graft,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('426', 'S7200', 'Alveloplasty,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('427', 'S7210', 'Alveloplasty,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('428', 'S7220', 'ridge,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('429', 'S7300', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('430', 'S7305', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('431', 'S7308', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('432', 'S7310', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('433', 'S7315', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('434', 'S7320', 'Removal,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('435', 'S7325', 'Removal,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('436', 'S7328', 'Removal,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('437', 'S7330', 'reduction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('438', 'S7335', 'reduction,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('439', 'S7340', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('440', 'S7350', 'Excision,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('441', 'S7400', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('442', 'S7410', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('443', 'S7600', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('444', 'S7610', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('445', 'S7700', 'Suture,');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('446', 'S7705', '');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('447', 'S8000', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('448', 'S8010', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('449', 'S8020', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('450', 'S8200', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('451', 'S8210', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('452', 'S8215', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('453', 'S8220', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('454', 'S8225', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('455', 'S8226', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('456', 'S8227', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('457', 'S8228', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('458', 'S8229', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('459', 'S8250', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('460', 'S8300', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('461', 'S8310', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('462', 'S8311', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('463', 'S8320', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('464', 'S8321', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('465', 'S8400', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('466', 'S8410', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('467', 'S8420', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('468', 'S8500', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('469', 'S8550', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('470', 'S8600', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('471', 'S8610', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('472', 'S8650', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('473', 'S8700', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('474', 'S8800', 'Braces,Clip');
INSERT INTO `importprocedures` (`id`, `code`, `keys`) VALUES ('475', 'S8910', 'Behaviour,');
