ALTER TABLE   activity_log    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   activitytracker    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   agent    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   agentcommission    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   agentcommissionreportparam    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;



ALTER TABLE   bank_details    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   benefit_master    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   benefit_member    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   booking    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   casereport    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   clinic    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   company    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   companyagent    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   companyhmoplan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   companyhmoplanrate    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   companypatientmember    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   consentform    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   copay    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   customer    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   customeractivity    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   customerdependants    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dentalcasesheet    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dentalchart    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dentalimage    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dentalprocedure    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dentalprocedure_chart    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dependantpayment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   dependantpolicyrenewal    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   doctor    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   doctortiming    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   enrollmentstatus    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   enrollstatus    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   groupregion    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   hmoplan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   hv_doctor    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   hv_treatment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   medicalnotes    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   medicaltest    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   medication    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   medicine    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   mediclaim    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   mediclaim_attachments    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   mediclaim_charts    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   mediclaim_procedures    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   mediclaim_signatures    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   membercount    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   memberpayment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   memberpolicyrenewal    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   monthly    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   ops_timing    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   otplog    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   patientmember    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   patientmemberdependants    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   payment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   paymenttxlog    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   preregister    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   prescription    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   procedurepriceplan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   prospect    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   provider    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   provider_region_plan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   providerbank    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   providercapitationreportparam    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   rlgdocument    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;



ALTER TABLE   role    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   role_default    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   rules    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   sessionlog    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   speciality    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   speciality_default    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   t_appointment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   t_appointment_archive    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   test1    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   tooth    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   toothcolor    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   tplan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   travel_log    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   treatment    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   treatmentnotes    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   treatmentplan    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   treatmentplannotes    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   urlproperties    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   wallet_plan_benefit    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;

ALTER TABLE   webmember    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
ALTER TABLE   webmemberdependants    CHANGE COLUMN `is_active` `is_active` CHAR(1) NULL DEFAULT 'T' ,    CHANGE COLUMN `created_on` `created_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `created_by` `created_by` INT(11) NULL DEFAULT 1 ,   CHANGE COLUMN `modified_on` `modified_on` DATETIME NULL DEFAULT now() ,   CHANGE COLUMN `modified_by` `modified_by` INT(11) NULL DEFAULT 1 ;
